import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getDatabase,ref,onValue,set}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyDVArU4b5-NiY861C48pK2ioCWxZvn8veY",authDomain:"smart-water-monitoring-s-bad82.firebaseapp.com",databaseURL:"https://smart-water-monitoring-s-bad82-default-rtdb.firebaseio.com",projectId:"smart-water-monitoring-s-bad82",storageBucket:"smart-water-monitoring-s-bad82.firebasestorage.app",messagingSenderId:"236717542324",appId:"1:236717542324:web:5ce4d5126f26d5cf8400e1"};
const db=getDatabase(initializeApp(firebaseConfig)),g=id=>document.getElementById(id);let voice=true,demo=false,levels=[75,45],previous=["",""],motor="OFF",motorMode="AUTO",lastTS=0,keys=new Set();
const chart=new Chart(g("waterChart").getContext("2d"),{type:"line",data:{labels:[],datasets:[{label:"Tank 1",data:[],tension:.4},{label:"Tank 2",data:[],tension:.4}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{min:0,max:100}}}});
function speak(x){if(voice&&"speechSynthesis"in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(x);u.rate=.9;speechSynthesis.speak(u)}}
function status(x){return x<=25?["🔴 LOW WATER","lowstatus","low",true]:x<=60?["🟡 WARNING","warnstatus","warning",false]:x<=89?["🟢 SAFE","safestatus","safe",false]:["🚨 OVERFLOW RISK","overflowstatus","overflow",true]}
function update(n,x){let s=status(x);g("water"+n).style.height=x+"%";g("percent"+n).innerText=x.toFixed(1)+"%";g("status"+n).innerText=s[0];g("status"+n).className="status "+s[1];g("tankInfo"+n).innerText="Current level: "+x.toFixed(1)+"%";return s}
function notice(type,msg){let key=type+msg;if(keys.has(key))return;keys.add(key);if(g("notificationHistory").innerText==="No notifications yet.")g("notificationHistory").innerHTML="";let d=document.createElement("div");d.className="notice "+type;d.innerHTML="<b>"+msg+"</b><br><small>"+new Date().toLocaleTimeString()+"</small>";g("notificationHistory").prepend(d)}
function history(a){chart.data.labels.push(new Date().toLocaleTimeString());chart.data.datasets[0].data.push(a[0]);chart.data.datasets[1].data.push(a[1]);if(chart.data.labels.length>12){chart.data.labels.shift();chart.data.datasets.forEach(d=>d.data.shift())}chart.update()}
function motorUI(){g("motorStatus").innerText=motor==="ON"?"🟢 MOTOR ON":"🔴 MOTOR OFF";g("motorDescription").innerText=motorMode==="AUTO"?"Automatic mode: Motor ON at ≤25%, OFF at ≥90%.":"Manual mode: command selected from dashboard."}
async function writeMotor(){if(!demo)try{await set(ref(db,"/control"),{motorState:motor,motorMode:motorMode,updatedAt:Date.now()})}catch(e){console.error(e)}}
function autoMotor(a){if(motorMode!=="AUTO")return;if(Math.min(...a)<=25&&motor!=="ON"){motor="ON";notice("low","🚰 Automatic control: Motor turned ON because a tank is low.");motorUI();writeMotor()}else if(Math.max(...a)>=90&&motor!=="OFF"){motor="OFF";notice("overflow","🚰 Automatic control: Motor turned OFF because a tank reached 90%.");motorUI();writeMotor()}}
function render(a){levels=a;let s=[update(1,a[0]),update(2,a[1])],alerts=[];s.forEach((x,i)=>{if(previous[i]!==x[0]&&previous[i]!==""){let t=i+1,l=a[i].toFixed(1);if(x[2]==="low"){notice("low","🔴 Tank "+t+" water level low ("+l+"%).");speak("Alert. Tank "+t+" water level is low. Current level is "+l+" percent.")}if(x[2]==="warning")notice("warning","🟡 Tank "+t+" warning level ("+l+"%).");if(x[2]==="overflow"){notice("overflow","🚨 Tank "+t+" overflow risk ("+l+"%).");speak("Warning. Tank "+t+" water level is critically high. Overflow risk detected.")}if(x[2]==="safe")notice("safe","🟢 Tank "+t+" returned to safe level ("+l+"%).")}previous[i]=x[0];if(x[2]==="low")alerts.push("🔴 Tank "+(i+1)+" is critically low at "+a[i].toFixed(1)+"%.");if(x[2]==="overflow")alerts.push("🚨 Tank "+(i+1)+" has overflow risk at "+a[i].toFixed(1)+"%.")});g("alertBox").innerHTML=alerts.length?alerts.join("<br>"):"🟢 Both tanks are operating normally.";autoMotor(a);history(a);g("lastUpdated").innerText=new Date().toLocaleString()}
g("voiceButton").onclick=()=>{voice=!voice;g("voiceButton").innerText=voice?"🔊 Voice ON":"🔇 Voice OFF"};
g("modeButton").onclick=()=>{demo=!demo;document.body.classList.toggle("demo-mode",demo);g("modeBadge").innerText=demo?"🎮 DEMO MODE":"📡 LIVE MODE";g("modeButton").innerText=demo?"📡 Switch to Live Mode":"🎮 Switch to Demo Mode";g("modeHelp").innerText=demo?"Demo values are controlled only in this browser. Firebase is not changed.":"Live data is read from Firebase.";if(demo){g("connectionDot").style.background="#22a559";g("connectionText").innerText="Demo Mode Active";g("sensorOnlineText").innerText="🟢 Demo sensor simulation";render(levels)}};
document.querySelectorAll(".plus").forEach(b=>b.onclick=()=>{let i=+b.dataset.tank-1;levels[i]=Math.min(100,levels[i]+5);render(levels)});
document.querySelectorAll(".minus").forEach(b=>b.onclick=()=>{let i=+b.dataset.tank-1;levels[i]=Math.max(0,levels[i]-5);render(levels)});
g("motorAutoButton").onclick=()=>{motorMode="AUTO";autoMotor(levels);motorUI();writeMotor()};g("motorOnButton").onclick=()=>{motorMode="MANUAL";motor="ON";motorUI();writeMotor()};g("motorOffButton").onclick=()=>{motorMode="MANUAL";motor="OFF";motorUI();writeMotor()};
function device(ok,d={}){g("firebaseStatus").innerText=ok?"🟢 Connected":"🔴 Error";g("arduinoStatus").innerText=d.arduino===false?"🔴 Offline":ok?"🟢 Connected":"🟡 Waiting";g("espStatus").innerText=d.esp8266===false?"🔴 Offline":ok?"🟢 Wi-Fi Connected":"🟡 Waiting";g("sensor1Status").innerText=d.tank1Sensor===false?"🔴 Offline":ok?"🟢 Active":"🟡 Waiting";g("sensor2Status").innerText=d.tank2Sensor===false?"🔴 Offline":ok?"🟢 Active":"🟡 Waiting"}
function sensorTime(ts){if(!ts){g("sensorOnlineText").innerText="🟡 Sensor timestamp not available yet";g("sensorUpdateText").innerText="Last update: waiting for equipment";return}lastTS=+ts;let s=Math.max(0,Math.floor((Date.now()-lastTS)/1000)),on=s<=30;g("sensorOnlineText").innerText=on?"🟢 Sensor Online • Live Data":"🔴 Sensor Offline";g("sensorUpdateText").innerText="Last update: "+s+" seconds ago"}
setInterval(()=>{if(!demo&&lastTS)sensorTime(lastTS)},1000);
onValue(ref(db,"/waterLevels"),snap=>{if(demo)return;let d=snap.val();if(!d){g("connectionText").innerText="Waiting for sensor";device(false);return}g("connectionDot").style.background="#22a559";g("connectionText").innerText="Firebase Connected";render([Math.max(0,Math.min(100,+d.tank1||0)),Math.max(0,Math.min(100,+d.tank2||0))]);sensorTime(d.lastUpdated||d.timestamp||0);device(true)},e=>{console.error(e);g("connectionText").innerText="Firebase Error";device(false)});
onValue(ref(db,"/deviceStatus"),s=>{if(!demo)device(true,s.val()||{})});
onValue(ref(db,"/control"),s=>{let d=s.val();if(d&&!demo){motor=d.motorState||motor;motorMode=d.motorMode||motorMode;motorUI()}});
motorUI();